--------------------------------------------------------------------------------
CREATE TABLE users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , created_at TIMESTAMP NOT NULL DEFAULT NOW()
    , deleted_at TIMESTAMP
    , blocked_at TIMESTAMP
    , username TEXT NOT NULL
    , password TEXT NOT NULL /* Salted SHA512 */

    , name TEXT NOT NULL
    , email TEXT
    , photo TEXT
);
CREATE INDEX users__deleted_at ON users (deleted_at);
CREATE INDEX users__created_at ON users (created_at) WHERE (deleted_at IS NULL);
CREATE INDEX users__blocked_at ON users (blocked_at) WHERE (deleted_at IS NULL);
CREATE UNIQUE INDEX users__username ON users (username) WHERE (deleted_at IS NULL);

--------------------------------------------------------------------------------
CREATE TABLE permissions
(
    permission_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , deleted_at TIMESTAMP
    , name TEXT NOT NULL
);
CREATE UNIQUE INDEX permissions__name ON permissions (name) WHERE (deleted_at IS NULL);

-- *
INSERT INTO permissions (name) VALUES ('plat:master');

--------------------------------------------------------------------------------
CREATE TABLE user_permissions
(
    user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE
    , permission_id INT NOT NULL REFERENCES permissions (permission_id) ON DELETE CASCADE
    , flag SMALLINT DEFAULT 0
    , PRIMARY KEY (user_id, permission_id)
);
CREATE INDEX user_permissions__flag ON user_permissions (user_id, flag);

--------------------------------------------------------------------------------
CREATE TABLE tokens
(
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , created_at TIMESTAMP NOT NULL DEFAULT NOW()
    , deleted_at TIMESTAMP
    , blocked_at TIMESTAMP
    , user_id BIGINT NOT NULL REFERENCES users (user_id)
    , token TEXT NOT NULL
    , name TEXT NOT NULL
);
CREATE INDEX tokens__deleted_at ON tokens (deleted_at);
CREATE INDEX tokens__user_id ON tokens (user_id) WHERE (deleted_at IS NULL);
CREATE UNIQUE INDEX tokens__token ON tokens (token) WHERE (deleted_at IS NULL);


--------------------------------------------------------------------------------
CREATE TABLE token_permissions
(
    token_id BIGINT NOT NULL REFERENCES tokens (token_id) ON DELETE CASCADE
    , permission_id INT NOT NULL REFERENCES permissions (permission_id) ON DELETE CASCADE
    , flag SMALLINT DEFAULT 0
    , PRIMARY KEY (token_id, permission_id)
);
CREATE INDEX token_permissions__flag ON token_permissions (token_id, flag);

--------------------------------------------------------------------------------
CREATE TABLE devices
(
    device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , created_at TIMESTAMP NOT NULL DEFAULT NOW()
    , last_activity TIMESTAMP
    , ipaddr TEXT
    , user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE
    , user_agent TEXT
    , webpush_subscription TEXT
    , token TEXT NOT NULL
    , secret TEXT DEFAULT NULL
);
CREATE UNIQUE INDEX devices__token ON devices (token);

--------------------------------------------------------------------------------
CREATE TABLE sessions
(
    session_id TEXT PRIMARY KEY
    , created_at TIMESTAMP NOT NULL DEFAULT NOW()
    , last_activity TIMESTAMP
    , device_id BIGINT REFERENCES devices (device_id) ON DELETE CASCADE
    , user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE
    , data TEXT
);
CREATE INDEX sessions__device_id ON sessions (device_id);
CREATE INDEX sessions__user_id ON sessions (user_id);

--------------------------------------------------------------------------------
CREATE TABLE suspicious_identifiers
(
    identifier TEXT NOT NULL PRIMARY KEY
    , next_attempt_at TIMESTAMP
    , last_attempt_at TIMESTAMP NOT NULL
    , count_failed INT DEFAULT 1
    , count_blocked INT DEFAULT 0
    , is_banned INT DEFAULT 0
);
